from setuptools import setup, find_namespace_packages

setup(
    name="agent-zero",
    version="0.1.0",
    packages=find_namespace_packages(include=["agent*", "python*"]),
    package_data={
        "agent": ["*.py"],
        "python": ["**/*.py"],
    },
    install_requires=[
        "ansio==0.0.1",
        "beautifulsoup4==4.12.3",
        "docker==7.1.0",
        "duckduckgo-search==6.1.12",
        "faiss-cpu==1.8.0.post1",
        "flask[async]==3.0.3",
        "flask-basicauth==0.2.0",
        "inputimeout==1.0.4",
        "langchain-core>=0.1.0",
        "langchain-anthropic==0.2.4",
        "langchain-community==0.3.5",
        "langchain-google-genai==2.0.4",
        "langchain-groq==0.2.1",
        "langchain-huggingface==0.1.2",
        "langchain-mistralai==0.2.1",
        "langchain-ollama==0.2.0",
        "langchain-openai==0.2.5",
        "lxml_html_clean==0.3.1",
        "markdown==3.7",
        "newspaper3k==0.2.8",
        "paramiko==3.4.0",
        "pypdf==4.3.1",
        "python-dotenv==1.0.1",
        "sentence-transformers==3.0.1",
        "unstructured==0.15.13",
        "unstructured-client==0.25.9",
        "webcolors==24.6.0",
        "pytest>=7.0.0",
        "typing-extensions>=4.0.0",
    ],
)
