{% set version = "14.0.6" %}

package:
  name: libcxx_and_libcxxabi
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
    sha256: 8b3cfd7bc695bd6cea0f37f53f0981f34f87496e79e2529874fd03a2f9dd3a8a
    patches:
      - patches/0001-libcxxabi-10.9-compatibility.patch  # [osx and x86_64]
      - patches/0002-Support-legacy-standalone-builds.patch
      # See https://lists.llvm.org/pipermail/libcxx-dev/2021-July/001172.html
      - patches/0003-Fix-ABI-compatibility-with-system.patch
      - patches/0004-custom-error-message-for-old-sdk.patch

build:
  number: 0
  skip: true  # [win]
  skip: True  # [linux and s390x]
  skip: True  # [py<30]

  ignore_run_exports:
    - libstdcxx-ng
  missing_dso_whitelist:
    - /usr/lib/libc++abi.dylib
    - /lib64/libpthread.so.0  # [linux]
    - /lib64/libc.so.6        # [linux]
    - /lib64/ld64.so.2        # [linux]
    - /lib64/libgcc_s.so.1    # [linux]
    - /lib64/ld-linux-aarch64.so.1  # [linux]
    - /lib64/ld-linux-x86-64.so.2   # [linux]

requirements:
  build:
    - cmake
    - make                    # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                  # [not osx]
    - patch                   # [unix]
    - m2-patch                # [win]
  host:
    - clangdev {{ version }}  # [not osx]
    - llvmdev {{ version }}   # [not osx]

outputs:
  - name: libcxx
    files:
      - include/c++
      - Library/include/c++
      - lib/libc++.*
      - lib/libc++fs.*
      - lib/libc++experimental.*
      - Library/bin/c++*.dll
      - Library/lib/c++*.lib
      - Library/lib/libc++*.lib
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("libcxxabi", exact=True) }}    # [linux]
      run:
        - {{ pin_subpackage("libcxxabi", exact=True) }}    # [linux]
    test:
      requires:
        - clang                  # [osx]
        - clangxx
        - ld64                   # [osx]
        - cctools                # [osx]
        - compiler-rt            # [osx]
        - llvm-tools             # [osx]
        - {{ compiler('cxx') }}  # [not osx]
      files:
        - test_sources
        - compile_test.sh   # [unix]
        - compile_test.bat  # [win]
      commands:
        # Dummy var for different hashes
        - echo {{ dummy_var }}                                    # [osx]
        - if not exist %LIBRARY_INC%\\c++\\v1\\iterator exit 1    # [win]
        - test -f $PREFIX/include/c++/v1/iterator                 # [unix]
        - bash compile_test.sh                                    # [unix]
        - compile_test.bat                                        # [win]
        # !!!!!!!!!!!! README !!!!!!!!!!!!!!!!!!
        # we do not ship libcxxabi on OSX - this breaks exception passing
        - if [ -f $PREFIX/lib/libc++abi.dylib ]; then exit 1; fi  # [osx]
        - test -f $PREFIX/lib/libc++abi.so                        # [linux]

      # Following 2 projects had issues with libc++, so check them
      # before releasing just to be sure.
      # downstreams:   # [osx]
      #  - python-symengine  # [osx]
      #  - openturns         # [osx]
      #  - libcxx-testing    # [osx]

  - name: libcxxabi
    build:
      skip: true  # [not linux]
      missing_dso_whitelist:
        - /lib64/libpthread.so.0
        - /lib64/libc.so.6
        - /lib64/ld64.so.2
        - /lib64/libgcc_s.so.1
        - /lib64/ld-linux-aarch64.so.1
        - /lib64/ld-linux-x86-64.so.2
    files:
      - lib/libc++abi.*
    requirements:
      run_constrained:
        - libcxx {{ version }}.*
    test:
      commands:
        - test -f $PREFIX/lib/libc++abi.so  # [linux]

about:
  home: https://libcxx.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: libcxx/LICENSE.TXT
  license_family: Apache
  summary: LLVM C++ standard library
  dev_url: https://github.com/llvm/llvm-project
  doc_url: https://libcxx.llvm.org/

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - jakirkham
    - isuruf
    - beckermr
    - timsnyder
    - h-vetinari
  feedstock-name: libcxx
