# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_06_m8gdsy6/clone/recipe, last modified Tue Oct  1 03:03:36 2024
# ------------------------------------------------

package:
  name: urllib3
  version: 2.2.3
source:
  sha256: e7d814a81dad81e6caf2ec9fdedb284ecc9c73076b62654547cc64ccdcae26e9
  url: https://pypi.io/packages/source/u/urllib3/urllib3-2.2.3.tar.gz
build:
  number: '0'
  script: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_06_m8gdsy6/croot/urllib3_1727769822458/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py312hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h80987f9_6
    - ca-certificates 2024.7.2 hca03da5_0
    - editables 0.3 py312hca03da5_0
    - expat 2.6.3 h313beb8_0
    - hatch-vcs 0.3.0 py312hca03da5_1
    - hatchling 1.21.1 py312hca03da5_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_1
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.15 h80987f9_0
    - packaging 24.1 py312hca03da5_0
    - pathspec 0.10.3 py312hca03da5_0
    - pip 24.2 py312hca03da5_0
    - pluggy 1.0.0 py312hca03da5_1
    - python 3.12.5 h99e199e_1
    - readline 8.2 h1a28f6b_0
    - setuptools 75.1.0 py312hca03da5_0
    - setuptools-scm 8.1.0 py312hca03da5_0
    - sqlite 3.45.3 h80987f9_0
    - tk 8.6.14 h6ba3021_0
    - trove-classifiers 2023.10.18 py312hca03da5_0
    - tzdata 2024a h04d1e81_0
    - wheel 0.44.0 py312hca03da5_0
    - xz 5.4.6 h80987f9_1
    - zlib 1.2.13 h18a0788_1
  run:
    - brotli-python >=1.0.9
    - pysocks >=1.5.6,<2.0,!=1.5.7
    - python >=3.12,<3.13.0a0
  run_constrained:
    - h2 >=4,<5
    - requests >=2.26.0
    - selenium >=4.4.3
    - zstandard >=0.18.0
test:
  commands:
    - pip check
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.util
  requires:
    - pip
about:
  description: 'urllib3 is a powerful, sanity-friendly HTTP client for Python. Much
    of the

    Python ecosystem already uses urllib3. urllib3 brings many critical features

    that are missing from the Python standard libraries, such as thread safety,

    connection pooling, client side ssl/tls verification, support for gzip and

    deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests

    and dealing with HTTP redirects.

    '
  dev_url: https://github.com/urllib3/urllib3
  doc_url: https://urllib3.readthedocs.io/
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 06471574-4a97-4a85-a3e1-919eecf846a3
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
    - sethmlarson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/urllib3-feedstock.git
  sha: 621b35fe32e9907c3de0da813cdedf85147f5d81
