# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /Users/builder/cbouss/perseverance-python-buildout/aggregate/boltons-feedstock/recipe, last modified Sun Nov  5 19:41:41 2023
# ------------------------------------------------

package:
  name: boltons
  version: 23.0.0
source:
  fn: boltons-23.0.0.tar.gz
  sha256: 9b2998cd9525ed472079c7dd90fbd216a887202e8729d5969d4f33878f0ff668
  url: https://github.com/mahmoud/boltons/archive/23.0.0.tar.gz
build:
  number: '0'
  script: /Users/builder/cbouss/perseverance-python-buildout/croot/boltons_1699240838368/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps -vv
  string: py312hca03da5_0
requirements:
  host:
    - bzip2 1.0.8 h620ffc9_4
    - ca-certificates 2023.08.22 hca03da5_0
    - expat 2.5.0 h313beb8_0
    - libcxx 14.0.6 h848a8c0_0
    - libffi 3.4.4 hca03da5_0
    - ncurses 6.4 h313beb8_0
    - openssl 3.0.12 h1a28f6b_0
    - pip 23.3 py312hca03da5_0
    - python 3.12.0 h99e199e_0
    - readline 8.2 h1a28f6b_0
    - setuptools 68.0.0 py312hca03da5_0
    - sqlite 3.41.2 h80987f9_0
    - tk 8.6.12 hb8d0fd4_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.41.2 py312hca03da5_0
    - xz 5.4.2 h80987f9_0
    - zlib 1.2.13 h5a0b063_0
  run:
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pytest -vv --doctest-modules boltons tests
    - pip check
  imports:
    - boltons
    - boltons.cacheutils
    - boltons.debugutils
    - boltons.dictutils
    - boltons.ecoutils
    - boltons.fileutils
    - boltons.formatutils
    - boltons.funcutils
    - boltons.gcutils
    - boltons.ioutils
    - boltons.iterutils
    - boltons.jsonutils
    - boltons.listutils
    - boltons.mathutils
    - boltons.mboxutils
    - boltons.namedutils
    - boltons.pathutils
    - boltons.queueutils
    - boltons.setutils
    - boltons.socketutils
    - boltons.statsutils
    - boltons.strutils
    - boltons.tableutils
    - boltons.tbutils
    - boltons.timeutils
    - boltons.typeutils
    - boltons.urlutils
  requires:
    - pip
    - pytest
  source_files:
    - boltons
    - pytest.ini
    - tests
about:
  description: "Boltons is a set of pure-Python utilities in the same spirit as \u2014\
    \ and yet conspicuously missing from \u2014 the standard library, including:\n\
    \n  - Atomic file saving, bolted on with fileutils\n  - A highly-optimized OrderedMultiDict,\
    \ in dictutils\n  - Two types of PriorityQueue, in queueutils\n  - Chunked and\
    \ windowed iteration, in iterutils\n  - A full-featured TracebackInfo type, for\
    \ representing stack traces, in tbutils\n  - A lightweight UTC timezone available\
    \ in timeutils.\n  - Recursive mapping for nested data transforms, with remap\n"
  dev_url: https://github.com/mahmoud/boltons
  doc_url: https://boltons.readthedocs.io/
  home: https://github.com/mahmoud/boltons
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'boltons should be builtins. Boltons is a set of over 160 BSD-licensed,
    pure-Python utilities in the same spirit as--and yet conspicuously missing from--the
    standard library.

    '
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - kalefranz
    - nicoddemus
