name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read # Optional, but can be helpful.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }} # Use your PAT here.

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images : ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name : Build and push Docker image 
      uses : docker/build-push-action@v4 
      with :
        context : ./docker/exe # Change this if your main Dockerfile is somewhere else!
        push : true 
        tags : ${{ steps.meta.outputs.tags }} 
